import Config
require Logger
# Do not print debug messages in production
config :logger,
  handle_sasl_reports: true

# TODO: to remove when the implementation will be detected
config :archethic,
       Archethic.Crypto.SharedSecretsKeystore,
       Archethic.Crypto.SharedSecretsKeystore.SoftwareImpl

config :archethic, Archethic.Governance.Pools,
  # TODO: provide the true addresses of the members
  initial_members: [
    technical_council: [],
    ethical_council: [],
    foundation: [],
    uniris: []
  ]

config :archethic,
       Archethic.Crypto.SharedSecretsKeystore,
       Archethic.Crypto.SharedSecretsKeystore.SoftwareImpl

config :archethic, Archethic.Utils.DetectNodeResponsiveness, timeout: 10_000

# For production, don't forget to configure the url host
# to something meaningful, Phoenix uses this information
# when generating URLs.
#
# Note we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the `mix phx.digest` task,
# which you should run after static files are built and
# before starting your production server.
config :archethic, ArchethicWeb.Endpoint,
  cache_static_manifest: "priv/static/cache_manifest.json",
  server: true,
  root: ".",
  version: Application.spec(:archethic, :vsn),
  check_origin: false,
  https: [
    cipher_suite: :strong,
    otp_app: :archethic,
    sni_fun: &ArchethicWeb.Domain.sni/1
  ]
